version: '3.8'
services:
  agenda-manager:
    image: ${CONTAINER_IMAGE}
    container_name: agenda-manager
    build: 
      context: ../
    ports:  
    - "9001:9001"
    networks:
    - network_local_server
networks:
  network_local_server:
    driver: bridge
    name: network_local_server